server:
  port: 8888
spring:
  profiles:
    active: development
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: <Username>
    password: <Password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


