server:
  port: 8888
spring:
  profiles:
    active: development
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: rmayore@livinggoods.org
    password: w9#5rY7aX4TH
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
redis:
  database: 0
  host: localhost
  port: 6379
  password: mypass
  timeout: 60000

