server:
  port: 8888
spring:
  profiles:
    active: development
  mail:
    host: localhost
    port: 1025
    username: mayorerobert@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
redis:
  database: 0
  host: localhost
  port: 6379
  password: mypass
  timeout: 60000
logging:
  level:
    root: INFO
    org:
      apache:
        kafka: WARN
