name: reviewdog
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest
    permissions:
      pull-requests: 'write'

    steps:
      - uses: actions/checkout@v3
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
